### ISSUE TITLE
pcb

### ISSUE THREAD

**Issue by yuliuyu** [wangguanan/Pytorch-Person-ReID-Baseline-PCB-Beyond-Part-Models#1]
Have you ever tried to add an RPP section to your  newest PCB module?Is it better than the original paper?

**Comment by wangguanan** [comment]
Hi, I don't add the RPP to our PCB implementation.
This project aims to provide a strong, clean and easily-extended re-id baseline. Thus, we don't add any complex algorithm to it.
We will keep updating this project for better performance, simpler algorithm, and more clean code.
