### ISSUE TITLE
what is the purpose of embeedings_list in models.py?

### ISSUE THREAD

**Issue by yian2271368** [wangguanan/Pytorch-Person-ReID-Baseline-PCB-Beyond-Part-Models#2]
hey, i found the embedding feautres are not used in your code, what is the purpose of embeding_list in models.py then?
thank you !

**Comment by wangguanan** [comment]
Hi, embedding features and embedding_list are not used here. I used to use it to compute the ranking loss in my original code, i.e. the triplet loss with batch hard.
For a fair comparison with the official PCB, I remove the triplet loss from my original code. You can also add a triplet loss to the embedding_list, and better performance will be achieved.
