### ISSUE TITLE
visualization map 

### ISSUE THREAD

**Issue by milliema** [wangguanan/Pytorch-Person-ReID-Baseline-PCB-Beyond-Part-Models#3]
In the published PCB paper, the author analyzed the highlight area maps of different branches (e.g. Fig.1 and Fig.7), do you know how to calculate these maps?

**Comment by wangguanan** [comment]
sorry, we didn't implement the function.
you may refer the official code for some help.
https://github.com/syfafterzy/PCB_RPP_for_reID
