### ISSUE TITLE
Abouts the results

### ISSUE THREAD

**Issue by Dtappledoghuati** [wangguanan/Pytorch-Person-ReID-Baseline-PCB-Beyond-Part-Models#4]
Time: 2020-08-05 20:51:44; Test Dataset: market, 
mAP: 0.4618259404352151 
Rank: [0.7131829  0.7891924  0.82214964 0.84649644 0.86252969 0.87618765
 0.88539192 0.89103325 0.89786223 0.90498812 0.90855107 0.91270784
 0.9165677  0.92072447 0.92309976 0.92666271 0.93022565 0.93289786
 0.93467933 0.93735154 0.9388361  0.94091449 0.94239905 0.94447743
 0.945962   0.94685273 0.94774347 0.94833729 0.94982185 0.9510095
 0.95190024 0.95249406 0.95308789 0.95368171 0.95427553 0.95486936
 0.9557601  0.95665083 0.95724466 0.9584323  0.95932304 0.95961995
 0.9608076  0.96110451 0.96140143 0.96140143 0.96169834 0.96169834
 0.96258907 0.96347981 0.96347981 0.96407363 0.96407363 0.96466746
 0.96466746 0.96526128 0.96555819 0.96585511 0.96585511 0.96615202
 0.96674584 0.96674584 0.96704276 0.96704276 0.96733967 0.96793349
 0.9682304  0.96852732 0.96882423 0.96912114 0.96941805 0.96971496
 0.97030879 0.9706057  0.97149644 0.97179335 0.97209026 0.97238717
 0.97238717 0.97238717 0.972981   0.972981   0.972981   0.972981
 0.97327791 0.97416865 0.97416865 0.97416865 0.97416865 0.97416865
 0.97446556 0.97446556 0.97446556 0.97505938 0.97505938 0.97535629
 0.97535629 0.97535629 0.97535629 0.97565321 0.97595012 0.97595012
 0.97624703 0.97624703 0.97624703 0.97624703 0.97624703 0.97624703
 0.97624703 0.97654394 0.97684086 0.97684086 0.97684086 0.97684086
 0.97713777 0.97743468 0.97743468 0.97773159 0.9780285  0.9780285
 0.97832542 0.97891924 0.97921615 0.97951306 0.97951306 0.97951306
 0.97951306 0.98010689 0.98010689 0.98010689 0.9804038  0.98070071
 0.98070071 0.98070071 0.98070071 0.98070071 0.98099762 0.98099762
 0.98099762 0.98129454 0.98129454 0.98129454 0.98129454 0.98129454
 0.98129454 0.98159145 0.98159145 0.98159145 0.98159145 0.98159145]

I got the above results. I don't understand why I get 150 ranks after 120 epochs. What do they represent?

**Comment by wangguanan** [comment]
mAP: 0.4618259404352151 
this is mean average precision score.

Rank: [0.7131829 0.7891924 ...
is CMC-k score

MAP and CMC are two popular evaluation metrics for person re-id.

cmc definition: https://cysu.github.io/open-reid/notes/evaluation_metrics.html

map definition: https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-ranked-retrieval-results-1.html
