### ISSUE TITLE
Result lower far than reported?

### ISSUE THREAD

**Issue by xiaopenfanz** [wangguanan/Pytorch-Person-ReID-Baseline-PCB-Beyond-Part-Models#5]
120epoch for p-k samples may be not enough?  what is the correct training params?

**Comment by wangguanan** [comment]
the experimental results show that 120 is enough for market and duke.

let me check the results.  I am re-running the code.

**Comment by wangguanan** [comment]
sorry for the bugs. I have fixed them by setting p=18 and 1epoch=200iters. please re-pull the repo, thanks.
